# Generated by Django 4.2.1 on 2023-08-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('t_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('t_subject', models.CharField(max_length=30)),
                ('t_age', models.IntegerField()),
            ],
        ),
    ]
